[package]
name = "ref0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2.7"
sha3 = "0.10.6"

[profile.test]
opt-level = 3            # Optimization level.
target-cpu = "native"
